title: "Ian Araújo | Portfólio"
name: "Ian Araújo"
description: "Estudante de Engenharia Elétrica - UFSJ"
url: "https://ianaraujof.github.io"
baseurl: ""
repository: "ianaraujof/ianaraujof.github.io"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

author:
  name: "Ian Araújo Figueiredo"
  avatar: "/images/perfil.jpg"
  bio: "Estudante de Engenharia Elétrica na UFSJ."
  location: "São João Del-Rei, MG"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ian-araujo-b6111b260/"

include:
  - _pages
  - _portfolio

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
